name: vibe_music
description: A new Flutter project.
publish_to: 'none' 
version: 0.9.0+9

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  youtube_explode_dart: ^1.12.4
  provider: ^6.0.5
  just_audio: ^0.9.32
  just_audio_background: ^0.0.1-beta.10
  google_fonts: ^4.0.4
  palette_generator: ^0.3.3+2
  intl: ^0.17.0
  miniplayer: ^1.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.6
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  expandable_page_view: ^1.0.17
  country_picker: ^2.0.20
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.0.2
  file_support: ^1.0.7
  permission_handler: ^10.4.3
  external_path: ^1.0.3
  package_info_plus: ^3.1.2
  flutter_swipe_action_cell: ^3.1.2
  connectivity_plus: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_intl:
  enabled: true
